### ISSUE TITLE
Instalar Banco de Dados

### ISSUE THREAD

**Issue by lucasfrag** [lucasfrag/Software-Engineering-II#2]
Time: @lucasfrag e @snoopeh
1) Verificar se o banco criado no DBDesignerFork está adequado ao projeto. Caso não esteja, realizar alterações necessárias e gerar novo banco;
2) Importar banco de dados criado com o DBDesignerFork;
3) Inserir dados nas tabelas.

**Comment by snoopeh** [comment]
Banco OK, (Inserir dados depois).
